# model
model_version: v1.2
pretrained_model_path: "models/PixArt-Sigma-XL-2-2K-MS.ckpt"
model_max_length: 300

noise_scheduler: rflow
sample_method: logit-normal
use_timestep_transform: True

vae_type: "OpenSoraVAE_V1_2"
vae_checkpoint: "models/OpenSora-VAE-v1.2/model.ckpt"
vae_dtype: bf16
vae_micro_batch_size: 4
vae_micro_frame_size: 17  # keep it unchanged for the best results

enable_flash_attention: True
use_recompute: True

# data
num_parallel_workers: 4
max_rowsize: 256

# precision
amp_level: "O2"
dtype: bf16
loss_scaler_type: static
init_loss_scale: 1

# training hyper-params
scheduler: "constant"
start_learning_rate: 2.e-5
end_learning_rate: 2.e-5
warmup_steps: 500

clip_grad: True
max_grad_norm: 1.0
use_ema: False

optim: "adamw_re"
optim_eps: 1e-15
weight_decay: 0.

epochs: 2
ckpt_save_interval: &save_interval 100

mask_ratios:
  random: 0.05
  interpolate: 0.005
  quarter_random: 0.005
  quarter_head: 0.005
  quarter_tail: 0.005
  quarter_head_tail: 0.005
  image_random: 0.025
  image_head: 0.05
  image_tail: 0.025
  image_head_tail: 0.025

bucket_config:
  # Structure: "resolution": { num_frames: [ keep_prob, batch_size ] }
  # Setting [ keep_prob, batch_size ] to [ 0.0, 0 ] forces longer videos into smaller resolution buckets
  "144p": { 34: [ 1.0, 1 ] }


# ---------- Validation ----------
validate: True
val_interval: 1
num_eval_timesteps: 5

val_csv_path:
val_video_folder:
val_text_embed_folder:

val_bucket_config:
  "144p": { 34: [ 1.0, 1 ] }
