# model
model_version: v1.2
pretrained_model_path: "models/PixArt-Sigma-XL-2-2K-MS.ckpt"
model_max_length: 300

enable_flash_attention: True
use_recompute: True

# data
num_parallel_workers: 8
max_rowsize: 256

# precision
amp_level: "O2"
dtype: bf16
loss_scaler_type: static
init_loss_scale: 1

# training hyper-params
scheduler: "cosine_decay"
start_learning_rate: 1.e-4
end_learning_rate: 2.e-5
warmup_steps: 500

clip_grad: True
max_grad_norm: 5.0
use_ema: True

optim: "adamw_re"
optim_eps: 1e-15
weight_decay: 0.

epochs: 2000
ckpt_save_interval: 100

mask_ratios:
  random: 0.05
  interpolate: 0.005
  quarter_random: 0.005
  quarter_head: 0.005
  quarter_tail: 0.005
  quarter_head_tail: 0.005
  image_random: 0.025
  image_head: 0.05
  image_tail: 0.025
  image_head_tail: 0.025

bucket_config:
  # Structure: "resolution": { num_frames: [ keep_prob, batch_size ] }
  # Setting [ keep_prob, batch_size ] to [ 0.0, 0 ] forces longer videos into smaller resolution buckets
  "144p": { 1: [ 1.0, 475 ], 51: [ 1.0, 51 ], 102: [ [ 1.0, 0.33 ], 27 ], 204: [ [ 1.0, 0.1 ], 13 ], 408: [ [ 1.0, 0.1 ], 6 ] }
  # ---
  "256": { 1: [ 0.4, 297 ], 51: [ 0.5, 20 ], 102: [ [ 0.5, 0.33 ], 10 ], 204: [ [ 0.5, 0.1 ], 5 ], 408: [ [ 0.5, 0.1 ], 2 ] }
  "240p": { 1: [ 0.3, 297 ], 51: [ 0.4, 20 ], 102: [ [ 0.4, 0.33 ], 10 ], 204: [ [ 0.4, 0.1 ], 5 ], 408: [ [ 0.4, 0.1 ], 2 ] }
  # ---
  "360p": { 1: [ 0.2, 141 ], 51: [ 0.15, 8 ], 102: [ [ 0.15, 0.33 ], 4 ], 204: [ [ 0.15, 0.1 ], 2 ], 408: [ [ 0.15, 0.1 ], 1 ] }
  "512": { 1: [ 0.1, 141 ] }
  # ---
  "480p": { 1: [ 0.1, 89 ] }
  # ---
  "720p": { 1: [ 0.05, 36 ] }
  "1024": { 1: [ 0.05, 36 ] }
  # ---
  "1080p": { 1: [ 0.1, 5 ] }
  # ---
  "2048": { 1: [ 0.1, 5 ] }
